[package]
name = "rambo"
description.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
glob = { workspace = true }
log = { workspace = true }
nom-exif = { workspace = true }
